### ISSUE TITLE
Auto refresh not work. (Sometimes)

### ISSUE THREAD

**Issue by Mishasama** [MarkM-dev/Previews-client#118]
After the page loading, the player fails to try to load the stream the first time.
![image](https://user-images.githubusercontent.com/54498172/211157404-0ba66fa3-e807-4da4-a344-66a3f2a61403.png)
![image](https://user-images.githubusercontent.com/54498172/211157439-a7ce220f-9d8e-4fa6-928a-a267af10a4e4.png)
Firefox 108

**Comment by MarkM-dev** [comment]
the stream shouldn't fail on the first try, if this happens all the time you should check your local/network environment variables.
i will add another check to maybe mitigate the issue.

**Comment by Mishasama** [comment]
> the stream shouldn't fail on the first try, if this happens all the time you should check your local/network environment variables. i will add another check to maybe know if this happens on page load? or switch? when exactly is this happening do you know?

Maybe on resolution auto switch. Or when network not stable.
I think you could pop up a notification after it fails 10 times in a row to remind the user that recovery is not possible.

And... Do you forget to upload the Firefox addon? It seems only the description has been updated.

**Comment by MarkM-dev** [comment]
fixed a few versions ago (added continues testing).
