### ISSUE TITLE
[Feature request] Picture in picture shows in viewport 

### ISSUE THREAD

**Issue by Nerxxy** [MarkM-dev/Previews-client#119]
When using PiP with YT streams on Twitch I would like to see the full screen view only take up the view port and not go behind the chat like it currently does, or have an extra button that only shows over the view port, maybe even an option to set the full screen button to either be view port only or how it is currently.

What I would like to see:
![image](https://user-images.githubusercontent.com/37718547/213969817-8a3668ea-624b-4f43-90b2-19ebab2bd204.png)

**Comment by MarkM-dev** [comment]
apparently that is not really allowed.
