### ISSUE TITLE
Sidebar Youtube channel preview doesn't work correctly

### ISSUE THREAD

**Issue by lmncaj** [MarkM-dev/Previews-client#121]
Sidebar Youtube channel preview doesn't work correctly.
It doen's show up.
It appears when collapse the sidebar.

![image](https://user-images.githubusercontent.com/44313991/217249869-334a9d6d-2e8e-4ae8-b14f-1871bdd68a32.png)
![image](https://user-images.githubusercontent.com/44313991/217250052-faff03b5-c6cc-43d9-9781-e094fa78af05.png)

**Comment by lmncaj** [comment]
i have no idea but it fixed after i post this
ill leave as it is

**Comment by MarkM-dev** [comment]
should be fixed now. the gift sub icon was probably the issue.
