### ISSUE TITLE
twitch stream lag when using full screen chat

### ISSUE THREAD

**Issue by Nerxxy** [MarkM-dev/Previews-client#124]
As of the past week or so I've been getting stream lags on multiple streams when having the chat up on full screen, I don't get any of this lag when using normal full screen.

I'm on Opera GX core: 96.0.4693.127, Windows 10 22H2 19045 (if it matters)

**Comment by MarkM-dev** [comment]
those features use default twitch components, check your other extensions if you have them, they might be causing that if they run code on the chat.
