### ISSUE TITLE
[Feature request] Move the Fast Forward (z) button under the chatbox next to the Chat Settings icon

### ISSUE THREAD

**Issue by Void48** [MarkM-dev/Previews-client#125]
It would be easier to click on it and I wouldn't have to move my mouse all the time whenever the stream gets delayed. I know I can use the (z) keyboard shortcut but I usually don't have my finger on the keyboard when watching streams so mouse is better
![image](https://github.com/MarkM-dev/Previews-client/assets/85196642/10ab6ed3-276a-479d-8889-41021fcd6c8f)

**Comment by MarkM-dev** [comment]
ill keep it in it's original space, there are people with their chat bar cluttered and adding more to it would not be helpful.
