### ISSUE TITLE
[Feature request] Return stream to 1.0 Speed after increasing playback speed to latest point in buffer

### ISSUE THREAD

**Issue by derickso** [MarkM-dev/Previews-client#126]
Youtube currently does this. In Youtube, if you go backwards in a stream's buffer, then increase the speed to eventually reach the latest point to the live stream, the speed returns to normal. Currently Previews causes the increase playback speed to remain even after reaching the latest point, causing the stream to continually rebuffer

**Comment by MarkM-dev** [comment]
it actually already does that (it work's real nice :)), if it's not working for you i would assume something on your client is different, perhaps a different extension blocking something?

try it on a clean browser profile without any other extensions.
reopen if persists.
also, you didn't provide any details about your setup but try that first.
