### ISSUE TITLE
Just a little kind request ;)

### ISSUE THREAD

**Issue by Daiv17** [MarkM-dev/Previews-client#13]
Not really an issue but a wish for future updates, if those are planned, to make a delay option before preview window pops up. 
Reason is while Im scrolling through "following channels" sidebar, the preview windows are coming up every time Im on the channel name...
thats it. 
tnx for the great extension!

**Comment by MarkM-dev** [comment]
i'll take a look at it for future versions.
glad to see you like the extension :)

**Comment by ARG-O** [comment]
Amazing! Great work, I just found the extension and I really like it.

**Comment by MarkM-dev** [comment]
Added in 9.2.
