### ISSUE TITLE
Cannot click Twitch Preview menu&buttons

### ISSUE THREAD

**Issue by immema** [MarkM-dev/Previews-client#55]
![image](https://user-images.githubusercontent.com/102508753/160348813-63438958-4b1f-4958-b6bf-7fd8b9fd5632.png)

When I open Twitch Preview in twitch websites, the menu opens under the channel block so I can't click any elements even after refresh, reopen chrome or reboot.

**Comment by MarkM-dev** [comment]
you might be using an outdated browser/browser version.
what are you using and what version?

**Comment by immema** [comment]
![image](https://user-images.githubusercontent.com/102508753/160561669-10861245-c732-4045-9d5f-263b9c9b7199.png)
I use the latest version of Chrome browser(99.0.4844.84 / 64bit).
Either in the Add-on bar(next to address bar) or twitch top nav. bar shows the same situation.

**Comment by MarkM-dev** [comment]
ok try this:

1. open the extension settings (as seen in your picture).
2. open the dev tools (F12).
3. go to the Console tab in the dev tools.
4. enter this in the console:
`document.querySelector('.tp-settings-container').zIndex = '99999999';
document.querySelector('#TPBodyEl').zIndex = '99999999';
document.querySelector('#TPBodyEl').display = 'block';`
5. press Enter.

did it fix it? (it will only make the change for this specific settings menu open, if you close and reopen it will go back to the bugged scenario).

**Comment by immema** [comment]
![issue](https://user-images.githubusercontent.com/102508753/160636802-6352267e-015f-4f42-a944-64494f9acc7b.gif)
sadly it doesn't works.... I entered that codes in the console and tried to interaction with the buttons(the cursor is invisible)
but still not response :(

does this situation relate to the red reply 'block'?

**Comment by MarkM-dev** [comment]
is this still happening?
can you disable all other extensions (all other extensions you have in the browser) and try again after refreshing the page?

**Comment by immema** [comment]
I found an instant solution. In chrome, press F12 to open a console window.
After deleting the following code, I can interaction with all those elements in twitch previews.
**<link href="https://static.twitchcdn.net/assets/core-41d8fe227c954bad221c.css" rel="stylesheet" crossorigin="anonymous">**
Still don't know how to use twitch previews in normal way :(

**Comment by MarkM-dev** [comment]
you didn't add the code.
